Updated the context description, it description and calendar object's instance method name in specs inspecting methods returning today's week-day name and week-day number. The "week_day_name_today" and "week_day_number_today" names looked bit ambiguos when using those in descriptions like "today's week date" or "yesterday's week date".Thus renamed week_day as weekday. However after these changes the spec failed with following errors:
  1) Calendar#weekday_name_today returns today's week-day name
     Failure/Error: expect(calendar.weekday_name_today).to eql(Time.now.strftime('%A'))
     NoMethodError:
       undefined method `weekday_name_today' for #<Calendar:0x000000018e21b8>
     # ./spec/calendar_spec.rb:14:in `block (3 levels) in <top (required)>'

  2) Calendar#weekday_number_today returns today's week-day number
     Failure/Error: expect(calendar.weekday_number_today).to eql(Time.now.wday)
     NoMethodError:
       undefined method `weekday_number_today' for #<Calendar:0x000000018e0a48>
     # ./spec/calendar_spec.rb:21:in `block (3 levels) in <top (required)>'