Added a failing spec
    context "#date_today" do
        it "returns today's date" do
            calendar = Calendar.new
            expect(calendar.date_today).to eql(Time.now.day)
        end
    end

failing with error

  1) Calendar#date_today returns today's date
     Failure/Error: expect(calendar.date_today).to eql(Time.now.day)
     NoMethodError:
       undefined method `date_today' for #<Calendar:0x00000001ecb228>
     # ./spec/calendar_spec.rb:7:in `block (3 levels) in <top (required)>'